NEI <- readRDS("summarySCC_PM25.rds");
SCC <- readRDS("Source_Classification_Code.rds");
vehicle = SCC[grepl("vehicle", SCC$Short.Name, ignore.case=TRUE),];
head(vehicle$SCC);
head(NEI$SCC);
SCCmrg <- merge(x = NEI, y = vehicle, by = "SCC");
totEmission <- aggregate(SCCmrg[, 'Emissions'], by=list(SCCmrg$year, SCCmrg$fips == "24510", SCCmrg$type == "ON-ROAD"), FUN=sum);
totEmission <- subset(totEmission, Group.2 == TRUE);
totEmission <- subset(totEmission, Group.3 == TRUE);
totLAEmission <- aggregate(SCCmrg[, 'Emissions'], by=list(SCCmrg$year, SCCmrg$fips == "06037", SCCmrg$type == "ON-ROAD"), FUN=sum);
totLAEmission <- subset(totLAEmission, Group.2 == TRUE);
totLAEmission <- subset(totLAEmission, Group.3 == TRUE);
head(totEmission);
head(totLAEmission);
rng <- range(c(totEmission$x, totLAEmission$x));
png(filename='HW2Exerciseplot6.png', width=480*2, height=480, units = "px");
par(mfrow=c(1,2));
barplot(totEmission$x, names.arg=totEmission$Group.1, ylim = rng, main=expression(paste('Total ON-ROAD Vehicle Emission of PM',''[2.5], 'In Baltimore, Maryland')),xlab='Year', ylab=expression(paste('PM', ''[2.5], ' in Tons')));
barplot(totLAEmission$x, names.arg=totLAEmission$Group.1, ylim = rng, main=expression(paste('Total ON-ROAD Vehicle Emission of PM',''[2.5], 'In LA, California')),xlab='Year', ylab=expression(paste('PM', ''[2.5], ' in Tons')));
dev.off();